<?php

namespace App\Support;

class ReportRegistry
{
    public static function all(): array
    {
        return [
            'penjualan-produk' => [
                'slug' => 'penjualan-produk',
                'label' => 'Penjualan & Produk',
                'icon' => 'Package',
                'group' => 'penjualan',
                'description' => 'Analisa jumlah produk yang di-order, top produk, dan tren penjualan.',
                'filters' => ['date_range', 'periode', 'brand'],
                'columns' => [
                    ['key' => 'nama_produk', 'label' => 'Produk'],
                    ['key' => 'total_qty', 'label' => 'Total Qty', 'format' => 'number'],
                    ['key' => 'total_order', 'label' => 'Jumlah Order', 'format' => 'number'],
                    ['key' => 'avg_qty', 'label' => 'Rata² per Order', 'format' => 'number'],
                    ['key' => 'total_value', 'label' => 'Total Nilai', 'format' => 'currency'],
                ],
                'chart' => ['type' => 'bar', 'x' => 'nama_produk', 'y' => 'total_qty', 'title' => 'Top Produk Berdasarkan Kuantitas'],
            ],
            'pelanggan' => [
                'slug' => 'pelanggan',
                'label' => 'Pelanggan',
                'icon' => 'Users',
                'group' => 'penjualan',
                'description' => 'Top pelanggan berdasarkan jumlah order dan total transaksi.',
                'filters' => ['date_range', 'brand'],
                'columns' => [
                    ['key' => 'kode', 'label' => 'Kode'],
                    ['key' => 'nama', 'label' => 'Nama'],
                    ['key' => 'nomor_hp', 'label' => 'HP'],
                    ['key' => 'total_order', 'label' => 'Total Order', 'format' => 'number'],
                    ['key' => 'total_qty', 'label' => 'Total Pcs', 'format' => 'number'],
                    ['key' => 'total_value', 'label' => 'Total Transaksi', 'format' => 'currency'],
                    ['key' => 'last_order', 'label' => 'Order Terakhir', 'format' => 'date'],
                ],
                'chart' => ['type' => 'bar', 'x' => 'nama', 'y' => 'total_value', 'title' => 'Top 10 Pelanggan Berdasarkan Nilai'],
            ],
            'wilayah' => [
                'slug' => 'wilayah',
                'label' => 'Wilayah',
                'icon' => 'MapPin',
                'group' => 'penjualan',
                'description' => 'Distribusi order per wilayah secara hirarkis (Provinsi, Kabupaten, Kecamatan, Desa).',
                'filters' => ['date_range', 'level_wilayah', 'brand'],
                'columns' => [
                    ['key' => 'provinsi', 'label' => 'Provinsi'],
                    ['key' => 'kabupaten', 'label' => 'Kabupaten/Kota'],
                    ['key' => 'kecamatan', 'label' => 'Kecamatan'],
                    ['key' => 'desa', 'label' => 'Desa/Kelurahan'],
                    ['key' => 'total_pelanggan', 'label' => 'Pelanggan', 'format' => 'number'],
                    ['key' => 'total_order', 'label' => 'Total Order', 'format' => 'number'],
                    ['key' => 'total_value', 'label' => 'Total Nilai', 'format' => 'currency'],
                ],
                'chart' => ['type' => 'bar', 'x' => 'kabupaten', 'y' => 'total_order', 'title' => 'Top Wilayah Berdasarkan Order'],
            ],
            'jenis-po' => [
                'slug' => 'jenis-po',
                'label' => 'Jenis PO',
                'icon' => 'PieChart',
                'group' => 'penjualan',
                'description' => 'Laporan perbandingan dan detail transaksi PO Normal, PO Spesial Order, dan PO Harga Reseller.',
                'filters' => ['date_range', 'jenis_po', 'status_po', 'brand'],
                'columns' => [
                    ['key' => 'no_po', 'label' => 'No PO'],
                    ['key' => 'nama_po', 'label' => 'Nama PO'],
                    ['key' => 'brand_nama', 'label' => 'Brand'],
                    ['key' => 'pelanggan', 'label' => 'Pelanggan'],
                    ['key' => 'tanggal_masuk', 'label' => 'Tgl Masuk', 'format' => 'date'],
                    ['key' => 'jenis_po', 'label' => 'Jenis PO', 'format' => 'badge'],
                    ['key' => 'pcs', 'label' => 'PCS', 'format' => 'number'],
                    ['key' => 'total_tagihan', 'label' => 'Total Tagihan', 'format' => 'currency'],
                    ['key' => 'status', 'label' => 'Status PO', 'format' => 'status_badge'],
                ],
            ],

            'status-po' => [
                'slug' => 'status-po',
                'label' => 'Status PO',
                'icon' => 'PackageCheck',
                'group' => 'operasional',
                'description' => 'Daftar PO dengan filter status dan periode.',
                'filters' => ['date_range', 'status_po', 'brand'],
                'columns' => [
                    ['key' => 'no_po', 'label' => 'No PO'],
                    ['key' => 'nama_po', 'label' => 'Nama PO'],
                    ['key' => 'pelanggan', 'label' => 'Pelanggan'],
                    ['key' => 'tanggal_masuk', 'label' => 'Tgl Masuk', 'format' => 'date'],
                    ['key' => 'deadline', 'label' => 'Deadline', 'format' => 'date'],
                    ['key' => 'pcs', 'label' => 'PCS', 'format' => 'number'],
                    ['key' => 'status', 'label' => 'Status', 'format' => 'status_badge'],
                    ['key' => 'total', 'label' => 'Total', 'format' => 'currency'],
                ],
            ],
            'monitoring-deadline' => [
                'slug' => 'monitoring-deadline',
                'label' => 'Monitoring Deadline',
                'icon' => 'AlarmClock',
                'group' => 'operasional',
                'description' => 'PO mendekati deadline produksi atau sudah terlambat.',
                'filters' => ['date_range', 'threshold', 'brand'],
                'columns' => [
                    ['key' => 'deadline_produksi', 'label' => 'Deadline Produksi', 'format' => 'date'],
                    ['key' => 'days', 'label' => 'Hari Produksi', 'format' => 'days_indicator'],
                    ['key' => 'deadline_customer', 'label' => 'Deadline Customer', 'format' => 'date'],
                    ['key' => 'days_customer', 'label' => 'Hari Customer', 'format' => 'days_indicator'],
                    ['key' => 'no_po', 'label' => 'No PO'],
                    ['key' => 'nama_po', 'label' => 'Nama PO'],
                    ['key' => 'brand_nama', 'label' => 'Brand'],
                    ['key' => 'pelanggan', 'label' => 'Pelanggan'],
                    ['key' => 'pcs', 'label' => 'PCS', 'format' => 'number'],
                    ['key' => 'jenis_printing', 'label' => 'Jenis Printing'],
                    ['key' => 'status', 'label' => 'Status', 'format' => 'status_badge'],
                ],
            ],
            'rijek' => [
                'slug' => 'rijek',
                'label' => 'Rijek Produksi',
                'icon' => 'AlertTriangle',
                'group' => 'produksi',
                'description' => 'Detail rijek produksi: jenis, tingkat, kendala.',
                'filters' => ['date_range', 'brand'],
                'columns' => [
                    ['key' => 'no_po', 'label' => 'No PO'],
                    ['key' => 'tahapan', 'label' => 'Tahapan'],
                    ['key' => 'jenis', 'label' => 'Jenis'],
                    ['key' => 'tingkat', 'label' => 'Tingkat', 'format' => 'badge'],
                    ['key' => 'jumlah', 'label' => 'Jumlah', 'format' => 'number'],
                    ['key' => 'kendala', 'label' => 'Kendala'],
                    ['key' => 'tanggal', 'label' => 'Tanggal', 'format' => 'date'],
                ],
            ],
            'refund' => [
                'slug' => 'refund',
                'label' => 'Refund',
                'icon' => 'RotateCcw',
                'group' => 'keuangan',
                'description' => 'Detail refund per periode, jenis masalah, dan status.',
                'filters' => ['date_range', 'refund_status', 'brand'],
                'columns' => [
                    ['key' => 'refund_number', 'label' => 'No Refund'],
                    ['key' => 'no_po', 'label' => 'No PO'],
                    ['key' => 'jenis_masalah', 'label' => 'Jenis Masalah'],
                    ['key' => 'jumlah_item', 'label' => 'Qty', 'format' => 'number'],
                    ['key' => 'nominal_refund', 'label' => 'Nominal', 'format' => 'currency'],
                    ['key' => 'status', 'label' => 'Status', 'format' => 'badge'],
                    ['key' => 'tanggal', 'label' => 'Diajukan', 'format' => 'date'],
                ],
            ],
            'pemasukan' => [
                'slug' => 'pemasukan',
                'label' => 'Pemasukan',
                'icon' => 'TrendingUp',
                'group' => 'keuangan',
                'description' => 'Detail semua pemasukan (otomatis dari PO + manual).',
                'filters' => ['date_range', 'is_auto', 'brand'],
                'columns' => [
                    ['key' => 'tanggal', 'label' => 'Tanggal', 'format' => 'date'],
                    ['key' => 'kategori', 'label' => 'Kategori'],
                    ['key' => 'keterangan', 'label' => 'Keterangan'],
                    ['key' => 'nominal', 'label' => 'Nominal', 'format' => 'currency'],
                    ['key' => 'sumber', 'label' => 'Sumber', 'format' => 'badge'],
                ],
                'chart' => ['type' => 'bar', 'x' => 'kategori', 'y' => 'nominal', 'title' => 'Pemasukan per Kategori'],
            ],
            'pengeluaran' => [
                'slug' => 'pengeluaran',
                'label' => 'Pengeluaran',
                'icon' => 'TrendingDown',
                'group' => 'keuangan',
                'description' => 'Detail semua pengeluaran (otomatis dari refund + manual).',
                'filters' => ['date_range', 'is_auto', 'brand'],
                'columns' => [
                    ['key' => 'tanggal', 'label' => 'Tanggal', 'format' => 'date'],
                    ['key' => 'kategori', 'label' => 'Kategori'],
                    ['key' => 'keterangan', 'label' => 'Keterangan'],
                    ['key' => 'nominal', 'label' => 'Nominal', 'format' => 'currency'],
                    ['key' => 'sumber', 'label' => 'Sumber', 'format' => 'badge'],
                ],
                'chart' => ['type' => 'bar', 'x' => 'kategori', 'y' => 'nominal', 'title' => 'Pengeluaran per Kategori'],
            ],
            'arus-kas-bank' => [
                'slug' => 'arus-kas-bank',
                'label' => 'Arus Kas & Rekonsiliasi Bank',
                'icon' => 'Landmark',
                'group' => 'keuangan',
                'description' => 'Pencocokan mutasi rekening koran dan arus kas bank berdasarkan rekening yang dimiliki oleh brand.',
                'filters' => ['date_range', 'brand', 'bank_accounts'],
                'columns' => [
                    ['key' => 'tanggal', 'label' => 'Tanggal', 'format' => 'date'],
                    ['key' => 'bank_info', 'label' => 'Rekening Bank'],
                    ['key' => 'brand_name', 'label' => 'Brand'],
                    ['key' => 'no_po', 'label' => 'No PO'],
                    ['key' => 'pelanggan', 'label' => 'Pelanggan'],
                    ['key' => 'tipe', 'label' => 'Tipe Transaksi'],
                    ['key' => 'debit', 'label' => 'Debit (Masuk)', 'format' => 'currency'],
                    ['key' => 'kredit', 'label' => 'Kredit (Keluar)', 'format' => 'currency'],
                    ['key' => 'status', 'label' => 'Status', 'format' => 'status_badge'],
                    ['key' => 'notes', 'label' => 'Catatan'],
                ],
                'chart' => ['type' => 'bar', 'x' => 'bank_info', 'y' => 'debit', 'title' => 'Total Dana Masuk per Rekening Bank'],
            ],
            'analisis-marketing' => [
                'slug' => 'analisis-marketing',
                'label' => 'Analisa Marketing',
                'icon' => 'TrendingUp',
                'group' => 'penjualan',
                'description' => 'Analisis gabungan Sumber Order dan Kategori Pelanggan untuk melacak omset.',
                'filters' => ['date_range', 'customer_type', 'sumber_order', 'brand', 'region', 'product'],
                'columns' => [
                    ['key' => 'sumber_order', 'label' => 'Sumber Order'],
                    ['key' => 'kategori_pelanggan', 'label' => 'Kategori Pelanggan'],
                    ['key' => 'total_order', 'label' => 'Jumlah Order', 'format' => 'number'],
                    ['key' => 'total_qty', 'label' => 'Total Qty', 'format' => 'number'],
                    ['key' => 'total_value', 'label' => 'Total Omset', 'format' => 'currency'],
                    ['key' => 'percentage', 'label' => 'Kontribusi (%)', 'format' => 'number'],
                ],
                'chart' => ['type' => 'bar', 'x' => 'sumber_order', 'y' => 'total_value', 'title' => 'Analisis Saluran Pemasaran Berdasarkan Omset'],
            ],
            'crm-churn' => [
                'slug' => 'crm-churn',
                'label' => 'Prediksi Churn & CRM',
                'icon' => 'Sparkles',
                'group' => 'penjualan',
                'description' => 'Prediksi risiko pelanggan kabur (churn) dan perkiraan tanggal pemesanan berikutnya berdasarkan riwayat transaksi.',
                'filters' => ['brand'],
                'columns' => [
                    ['key' => 'kode', 'label' => 'Kode Pelanggan'],
                    ['key' => 'nama', 'label' => 'Nama Pelanggan'],
                    ['key' => 'total_order', 'label' => 'Total Order', 'format' => 'number'],
                    ['key' => 'avg_interval_text', 'label' => 'Siklus Order (Rata-rata)'],
                    ['key' => 'recency_days', 'label' => 'Hari Sejak Order Terakhir', 'format' => 'number'],
                    ['key' => 'next_order_pred', 'label' => 'Prediksi Order Berikutnya', 'format' => 'date'],
                    ['key' => 'risk_level', 'label' => 'Tingkat Risiko Churn', 'format' => 'churn_status'],
                    ['key' => 'monetary_loss', 'label' => 'Potensi Omset Hilang', 'format' => 'currency'],
                    ['key' => 'whatsapp_action', 'label' => 'Aksi Follow Up', 'format' => 'whatsapp_action'],
                ],
            ],
            'crm-seasonal' => [
                'slug' => 'crm-seasonal',
                'label' => 'Pengingat Order Musiman',
                'icon' => 'Calendar',
                'group' => 'penjualan',
                'description' => 'Mendeteksi pelanggan yang memesan untuk event tahunan di bulan yang sama tahun lalu untuk penawaran repeat order.',
                'filters' => ['brand'],
                'columns' => [
                    ['key' => 'kode', 'label' => 'Kode Pelanggan'],
                    ['key' => 'nama', 'label' => 'Nama Pelanggan'],
                    ['key' => 'order_tahun_lalu', 'label' => 'No PO Tahun Lalu'],
                    ['key' => 'tanggal_order_lalu', 'label' => 'Tanggal Order Lalu', 'format' => 'date'],
                    ['key' => 'nilai_order_lalu', 'label' => 'Nilai Order Lalu', 'format' => 'currency'],
                    ['key' => 'whatsapp_action', 'label' => 'Aksi Follow Up', 'format' => 'whatsapp_action'],
                ],
            ],
            'kinerja-produksi' => [
                'slug' => 'kinerja-produksi',
                'label' => 'Kinerja Produksi',
                'icon' => 'Gauge',
                'group' => 'produksi',
                'description' => 'Laporan kinerja produksi: mengukur durasi dan keterlambatan pengerjaan tahapan progress PO.',
                'filters' => ['date_range', 'lateness_status', 'brand'],
                'columns' => [
                    ['key' => 'no_po', 'label' => 'No PO'],
                    ['key' => 'nama_po', 'label' => 'Nama PO'],
                    ['key' => 'brand_nama', 'label' => 'Brand'],
                    ['key' => 'pelanggan', 'label' => 'Pelanggan'],
                    ['key' => 'tanggal_masuk', 'label' => 'Tgl Masuk', 'format' => 'date'],
                    ['key' => 'deadline', 'label' => 'Deadline', 'format' => 'date'],
                    ['key' => 'pcs', 'label' => 'PCS', 'format' => 'number'],
                    ['key' => 'status', 'label' => 'Status PO', 'format' => 'status_badge'],
                    ['key' => 'keterlambatan', 'label' => 'Keterlambatan'],
                    ['key' => 'durasi_total', 'label' => 'Durasi Total'],
                ],
            ],
        ];
    }

    public static function find(string $slug): ?array
    {
        return self::all()[$slug] ?? null;
    }

    public static function groups(): array
    {
        return [
            'penjualan' => 'Penjualan & Pelanggan',
            'operasional' => 'Operasional & PO',
            'produksi' => 'Produksi & Rijek',
            'keuangan' => 'Keuangan',
        ];
    }
}
